import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PublicLayoutWrapper from "@/components/PublicLayoutWrapper";
import { getCompanies, getLatest } from "@/lib/data";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "ForecastPH | Educational Stock Forecasting",
  description: "Educational PSE stock price forecasts generated by an automated ML pipeline.",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const [companies, latest] = await Promise.all([getCompanies(), getLatest()]);

  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                var theme = localStorage.getItem('theme');
                if (theme === 'light') {
                  document.documentElement.classList.remove('dark');
                } else {
                  document.documentElement.classList.add('dark');
                }
              } catch (_) {}
            `,
          }}
        />
      </head>
      <body className={`${inter.variable} bg-dark-bg text-slate-300 font-sans antialiased overflow-x-hidden min-h-screen flex flex-col`}>
        <PublicLayoutWrapper companies={companies} latest={latest}>
          {children}
        </PublicLayoutWrapper>
      </body>
    </html>
  );
}
