import { formatDateTime } from "@/lib/format";
import type { LatestData } from "@/lib/types";

export default function EducationalBanner({ latest }: { latest: LatestData | null }) {
  return (
    <div className="bg-brand-900/50 border-b border-brand-500/30 text-center py-2 px-4 text-xs sm:text-sm text-brand-100 mt-16 relative z-40">
      <strong>Educational Purpose Only:</strong> Forecasts are generated by an automated
      machine-learning pipeline from historical PSE data and should not be used as financial advice.
      {latest?.lastRunAt && (
        <span className="block sm:inline sm:ml-2 text-brand-300/80">
          Data last refreshed: {formatDateTime(latest.lastRunAt)} (status: {latest.status})
        </span>
      )}
    </div>
  );
}
